package Bank;
// Generated 2017-1-9 16:25:43 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Account generated by hbm2java
 */
public class Account  implements java.io.Serializable {


     private String username;
     private String accounttype;
     private BigDecimal balacnce;
     private String rate;

    public Account() {
    }

	
    public Account(String username, String accounttype, String rate) {
        this.username = username;
        this.accounttype = accounttype;
        this.rate = rate;
    }
    public Account(String username, String accounttype, BigDecimal balacnce, String rate) {
       this.username = username;
       this.accounttype = accounttype;
       this.balacnce = balacnce;
       this.rate = rate;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getAccounttype() {
        return this.accounttype;
    }
    
    public void setAccounttype(String accounttype) {
        this.accounttype = accounttype;
    }
    public BigDecimal getBalacnce() {
        return this.balacnce;
    }
    
    public void setBalacnce(BigDecimal balacnce) {
        this.balacnce = balacnce;
    }
    public String getRate() {
        return this.rate;
    }
    
    public void setRate(String rate) {
        this.rate = rate;
    }




}


