package Bank;
// Generated 2017-1-9 16:25:43 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Banktransaction generated by hbm2java
 */
public class Banktransaction  implements java.io.Serializable {


     private String accountid;
     private String accountgetter;
     private String accountsender;
     private String banktransaction;
     private Date transactiondate;
     private BigDecimal transactiondmoney;

    public Banktransaction() {
    }

    public Banktransaction(String accountid, String accountgetter, String accountsender, String banktransaction, Date transactiondate) {
       this.accountid = accountid;
       this.accountgetter = accountgetter;
       this.accountsender = accountsender;
       this.banktransaction = banktransaction;
       this.transactiondate = transactiondate;
    }
   
    public String getAccountid() {
        return this.accountid;
    }
    
    public void setAccountid(String accountid) {
        this.accountid = accountid;
    }
    public String getAccountgetter() {
        return this.accountgetter;
    }
    
    public void setAccountgetter(String accountgetter) {
        this.accountgetter = accountgetter;
    }
    public String getAccountsender() {
        return this.accountsender;
    }
    
    public void setAccountsender(String accountsender) {
        this.accountsender = accountsender;
    }
    public String getBanktransaction() {
        return this.banktransaction;
    }
    
    public void setBanktransaction(String banktransaction) {
        this.banktransaction = banktransaction;
    }
    public Date getTransactiondate() {
        return this.transactiondate;
    }
    
    public void setTransactiondate(Date transactiondate) {
        this.transactiondate = transactiondate;
    }

    public BigDecimal getTransactiondmoney() {
        return transactiondmoney;
    }

    public void setTransactiondmoney(BigDecimal transactiondmoney) {
        this.transactiondmoney = transactiondmoney;
    }

    


}


