package Bank;
// Generated 2017-1-9 16:25:43 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Loan generated by hbm2java
 */
public class Loan  implements java.io.Serializable {


     private String username;
     private String loantype;
     private String rates;
     private BigDecimal payment;

    public Loan() {
    }

	
    public Loan(String accountid, String username, String loantype, String rates) {

        this.username = username;
        this.loantype = loantype;
        this.rates = rates;
    }
    public Loan(String accountid, String username, String loantype, String rates, BigDecimal payment) {

       this.username = username;
       this.loantype = loantype;
       this.rates = rates;
       this.payment = payment;
    }
   

    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getLoantype() {
        return this.loantype;
    }
    
    public void setLoantype(String loantype) {
        this.loantype = loantype;
    }
    public String getRates() {
        return this.rates;
    }
    
    public void setRates(String rates) {
        this.rates = rates;
    }
    public BigDecimal getPayment() {
        return this.payment;
    }
    
    public void setPayment(BigDecimal payment) {
        this.payment = payment;
    }




}


